from typing import List
from pydantic import BaseModel, Field
from langchain.agents.structured_output import ToolStrategy
from dotenv import load_dotenv
load_dotenv()

from langchain.agents import create_agent
from langchain.tools import tool
from langchain_core.messages import HumanMessage
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_tavily import TavilySearch

class Source(BaseModel):
    """Schema for a source used by the agent."""
    url: str = Field(description="The URL of the source")

class AgentResponse(BaseModel):
    """Schema for the agent's response with answer and sources."""
    answer: str = Field(description="The answer generated by the agent")
    sources: List[Source] = Field(default_factory=list, description="List of sources used to generate the answer")



llm = ChatGoogleGenerativeAI(model="gemini-2.5-pro")
tools = [TavilySearch()]
agent = create_agent(model=llm, tools=tools, response_format=ToolStrategy(AgentResponse))

def main():
    print("Hello from langchain-course!")
    response = agent.invoke({"messages":HumanMessage(content="search fro 3 job postings for python developer in dallas tx on linkedin and list their details")})
    print(response["structured_response"])

if __name__ == "__main__":
    main()
